name: Run containers

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Pull an image
      run: docker pull stodkar898/lenze-lab:latest

    - name: Run docker container 
      run: docker container run -d -p 8081:8081 --name my-app stodkar898/lenze-lab:latest
      
    - name: Run Docker Compose
      run: docker-compose -f docker-compose.yml up -d .
