name: Build & Push an image to dockerhub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Pull an image

      run: docker pull stodkar898/lenze-lab:latest

    - name: Run docker container 
      run: docker container run -d -p 80:80 --name my-app --image stodkar898/lenze-lab:latest
