name: Build & Push an image to dockerhub

on:    
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4.0.3
      with:
        node-version: '16'
    - name: find dir
      run: cd app
    - name: Install dependencies
      run:  npm install
    - name: Build the Docker image
      run: docker build -t my-app:latest .       
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
   
    - name: Tag an image
      run: docker tag my-app:latest stodkar898/lenze-lab
    - name: Push an image to docker hub
      run: docker push stodkar898/lenze-lab:latest
 

      

